### ISSUE TITLE
com.ibm.bpm.mon.oi.json.JSONException: wle:tracked-field is not an array.

### ISSUE THREAD

**Issue by sundag** [ibmbpm/bpm_analytics#1]
When you selected only one KPI data or checked only one tracked-field in process. You may meet below exception when processing message with BPMEventEmitter:
BPMEventEmitt E com.ibm.bpm.mon.oi.BPMEventEmitterMDB OnMessage E: Got unexpected exception when sending message.
                                 com.ibm.bpm.mon.oi.json.JSONException: wle:tracked-field is not an array.
	at com.ibm.bpm.mon.oi.json.JSONObject.getJSONArray(JSONObject.java:238)
	at com.ibm.bpm.mon.oi.transform.TrackingPointHandler.transform(TrackingPointHandler.java:62)
	at com.ibm.bpm.mon.oi.transform.AbstractTransformHandler.doWork(AbstractTransformHandler.java:86)

May happen.

**Comment by zhangs-ibm** [comment]
fixed at the development build, will be included at the v1.0.1
