### ISSUE TITLE
org.xml.sax.SAXParseException: Invalid byte 2 of 4-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by sundag** [ibmbpm/bpm_analytics#2]
When you use some special character in process and the default encoding for the server local is not UTF-8. Exception in below may happen:
 org.xml.sax.SAXParseException: Invalid byte 2 of 4-byte UTF-8 sequence.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at com.ibm.bpm.mon.oi.json.XML.convertToDOM(XML.java:58)

**Comment by zhangs-ibm** [comment]
fixed at the development build, will be included at the v1.0.1
